### ISSUE TITLE
option to keep also optional in types

### ISSUE THREAD

**Issue by vlastoun** [rokkie/dtsgenerator-optional-as-null#1]
Hello,
nice job with plugin!
Is there any option to also keep "optional" value?
I mean:
```
interface Something {
  param?: string | null
}
```

**Comment by rokkie** [comment]
Hi @vlastoun

Currently there is no such option. As you may expect, I initially created this to solve my own problem.
An option to keep optionals seems reasonable enough, but I don't know when I have time to implement this.
If you need this soon, PR is always welcome.

**Comment by rokkie** [comment]
I added a `keepOptionals` config option in `v0.1.2`
